spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pdfpoolbot
    password:
    username:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
pdf-pool-bot:
  telegram:
    bot:
      token:
      username:
